const cartItemData = [
     { cart_id: 1, product_id: 1, quantity: 2 },
     { cart_id: 1, product_id: 2, quantity: 3 },
     { cart_id: 1, product_id: 3, quantity: 4 },
     { cart_id: 1, product_id: 4, quantity: 5 },
     { cart_id: 1, product_id: 5, quantity: 6 },
     { cart_id: 2, product_id: 1, quantity: 2 },
     { cart_id: 2, product_id: 2, quantity: 3 },
     { cart_id: 2, product_id: 3, quantity: 4 },
     { cart_id: 2, product_id: 4, quantity: 5 },
     { cart_id: 2, product_id: 5, quantity: 6 },
     { cart_id: 3, product_id: 1, quantity: 2 },
     { cart_id: 3, product_id: 2, quantity: 3 },
     { cart_id: 3, product_id: 3, quantity: 4 },
     { cart_id: 3, product_id: 4, quantity: 5 },
     { cart_id: 3, product_id: 5, quantity: 6 },
     { cart_id: 4, product_id: 1, quantity: 2 },
     { cart_id: 4, product_id: 2, quantity: 3 },
     { cart_id: 4, product_id: 3, quantity: 4 },
     { cart_id: 4, product_id: 4, quantity: 5 },
     { cart_id: 4, product_id: 5, quantity: 6 },
     { cart_id: 5, product_id: 1, quantity: 2 },
     { cart_id: 5, product_id: 2, quantity: 3 },
     { cart_id: 5, product_id: 3, quantity: 4 },
     { cart_id: 5, product_id: 4, quantity: 5 },
     { cart_id: 5, product_id: 5, quantity: 6 },
   ];
   
   module.exports = cartItemData;