const productData = [
     {
          id: "1",
          name: "Product 1",
          description: "This is product 1",
          price: 200,
          stock: 10,
          image_url: "https://via.placeholder.com/200",
          categories: "Category1",
          vendor_id: 3,
     },
     {
          id: "2",
          name: "Product 2",
          description: "This is product 2",
          price: 200,
          stock: 20,
          image_url: "https://via.placeholder.com/200",
          categories: "Category2",
          vendor_id: 3,
     },
     {
          id: "3",
          name: "Product 3",
          description: "This is product 3",
          price: 300,
          stock: 30,
          image_url: "https://via.placeholder.com/200",
          categories: "Category3",
          vendor_id: 6,
     },
     {
          id: "4",
          name: "Product 4",
          description: "This is product 4",
          price: 400,
          stock: 40,
          image_url: "https://via.placeholder.com/200",
          categories: "Category4",
          vendor_id: 4,
     },
     {
          id: "5",
          name: "Product 5",
          description: "This is product 5",
          price: 500,
          stock: 50,
          image_url: "https://via.placeholder.com/200",
          categories: "Category5",
          vendor_id: 4,
     },
     {
          id: "6",
          name: "Product 6",
          description: "This is product 6",
          price: 600,
          stock: 60,
          image_url: "https://via.placeholder.com/200",
          categories: "Category6",
          vendor_id: 5,
          is_active: false,
     },
];

module.exports = productData;
