const productData = [
     {
          id: "1",
          name: "Fuji Apples",
          description:
               "Fuji apples are a crisp, sweet apple with a juicy texture. They are a great snacking apple and are delicious in salads, pies, sauces, and baked goods.",
          price: 1.5,
          stock: 200,
          image_url: "https://images.publixcdn.com/pct/images/products/20000/023833-600x600-A.jpg",
          category_id: 1,
          vendor_id: 1,
     },
     {
          id: "2",
          name: "Organic Granny Smith Apples",
          description:
               "Granny Smith apples are a tart apple with a firm texture. They are bright green in color and are excellent for both cooking and snacking.",
          price: 2.0,
          stock: 150,
          image_url: "https://images.publixcdn.com/pct/images/products/25000/025858-600x600-A.jpg",
          category_id: 1,
          vendor_id: 1,
     },
     {
          id: "3",
          name: "Product 3",
          description: "This is product 3",
          price: 300,
          stock: 30,
          image_url: "https://via.placeholder.com/200",
          categories: "Category3",
          vendor_id: 6,
     },
     {
          id: "4",
          name: "Product 4",
          description: "This is product 4",
          price: 400,
          stock: 40,
          image_url: "https://via.placeholder.com/200",
          categories: "Category4",
          vendor_id: 4,
     },
     {
          id: "5",
          name: "Product 5",
          description: "This is product 5",
          price: 500,
          stock: 50,
          image_url: "https://via.placeholder.com/200",
          categories: "Category5",
          vendor_id: 4,
     },
     {
          id: "6",
          name: "Product 6",
          description: "This is product 6",
          price: 600,
          stock: 60,
          image_url: "https://via.placeholder.com/200",
          categories: "Category6",
          vendor_id: 5,
          is_active: false,
     },
     {
          id: "7",
          name: "Product 7",
          description: "This is product 7",
          price: 700,
          stock: 70,
          image_url: "https://via.placeholder.com/200",
          categories: "Category7",
          vendor_id: 5,
     },
     {
          id: "8",
          name: "Product 8",
          description: "This is product 8",
          price: 800,
          stock: 80,
          image_url: "https://via.placeholder.com/200",
          categories: "Category8",
          vendor_id: 6,
     },
     {
          id: "9",
          name: "Product 9",
          description: "This is product 9",
          price: 900,
          stock: 90,
          image_url: "https://via.placeholder.com/200",
          categories: "Category9",
          vendor_id: 6,
     },
     {
          id: "10",
          name: "Product 10",
          description: "This is product 10",
          price: 1000,
          stock: 100,
          image_url: "https://via.placeholder.com/200",
          categories: "Category10",
          vendor_id: 3,
     },
     {
          id: "11",
          name: "Product 11",
          description: "This is product 11",
          price: 1100,
          stock: 110,
          image_url: "https://via.placeholder.com/200",
          categories: "Category11",
          vendor_id: 3,
     },
     {
          id: "12",
          name: "Product 12",
          description: "This is product 12",
          price: 1200,
          stock: 120,
          image_url: "https://via.placeholder.com/200",
          categories: "Category12",
          vendor_id: 3,
     },
     {
          id: "13",
          name: "Product 13",
          description: "This is product 13",
          price: 1300,
          stock: 130,
          image_url: "https://via.placeholder.com/200",
          categories: "Category13",
          vendor_id: 4,
          is_active: true,
     },
     {
          id: "14",
          name: "Product 14",
          description: "This is product 14",
          price: 1400,
          stock: 140,
          image_url: "https://via.placeholder.com/200",
          categories: "Category14",
          vendor_id: 4,
          is_active: false,
     },
     {
          id: "15",
          name: "Product 15",
          description: "This is product 15",
          price: 1500,
          stock: 150,
          image_url: "https://via.placeholder.com/200",
          categories: "Category15",
          vendor_id: 4,
          is_active: true,
     },
     {
          id: "16",
          name: "Product 16",
          description: "This is product 16",
          price: 1600,
          stock: 160,
          image_url: "https://via.placeholder.com/200",
          categories: "Category16",
          vendor_id: 4,
          is_active: false,
     },
];

module.exports = productData;
